repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: detect-private-key
    -   id: check-added-large-files
-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
    -   id: detect-secrets
        args: ['--baseline', '.secrets.baseline']
        exclude: package.json.lock
-   repo: local
    hooks:
    -   id: detect-phi-ssn
        name: Detect PHI (SSN)
        entry: (?:\d{3}-\d{2}-\d{4})
        language: pygrep
        types: [text]
